
#commande le bouton de l'amperage de la borne via le bouton vituel au traver du script qui est apellé si dessous
- id: sync_charge_current_with_virtual
  alias: "Sync Charge Current with Virtual"
  trigger:
    - platform: state
      entity_id: input_number.chargeurvoiture_set_chargevirtuel_current
  condition: []
  action:
    - service: script.adjust_charge_current
      data:
        target_value: "{{ trigger.to_state.state | float }}"




# Automatisation pour la gestion de la charge de la voiture électrique Zoé
- id: Gestion_de_la_charge_Zoe
  alias: "Gestion de la charge voiture electrique"
  trigger:
    # Déclencheurs pour tous les modes (se déclenche lorsque l'un des états change)
    - platform: state
      entity_id:
        - sensor.fl995hk_batterie             # Niveau de batterie de la Zoé
        - input_number.zoe_coupure_pourcentage # Pourcentage de coupure défini
        - sensor.chargeurvoiture_status       # Statut du chargeur de la voiture
        - input_select.SelecteurChargeurVE    # Sélecteur du mode de charge
        - sensor.combined_power_pylontech_voltronic     # Puissance solaire disponible
        - sensor.combined_battery_soc         # État de charge de la batterie maison
    # Déclencheurs pour le début et la fin de la période solaire
    - platform: template
      value_template: >-
        {{ states('sensor.time') == (state_attr('sun.sun', 'next_rising') | as_datetime + timedelta(hours=1)).strftime('%H:%M') }}
    - platform: template
      value_template: >-
        {{ states('sensor.time') == (state_attr('sun.sun', 'next_setting') | as_datetime - timedelta(hours=1)).strftime('%H:%M') }}

  condition: []
  
  action:
    - choose:
###################  Mode "On No limits" : Démarrage immédiat de la charge , sous aucunes reserve. ###################
        - conditions:
            - condition: template
              value_template: "{{ is_state('input_select.SelecteurChargeurVE', 'On No Limits') }}"
          sequence:
            # Démarre la charge de la Zoé
            - service: select.select_option
              data:
                entity_id: select.chargeurvoiture_toggle_charging
                option: "Start charging"
                
################## Mode "On limited" : Démarrage de la charge et stop en fonction du pourcentage de la batterie
        - conditions:
            - condition: template
              value_template: "{{ is_state('input_select.SelecteurChargeurVE', 'On Limited') }}"
          sequence:
            - choose:
                # Démarrer la charge si la batterie de la Zoé est sous le seuil défini
                - conditions:
                    - condition: template
                      value_template: "{{ states('sensor.fl995hk_batterie') | float < states('input_number.zoe_coupure_pourcentage') | float }}" # Batterie Zoé sous le seuil défini
                    - condition: template
                      value_template: "{{ not is_state('sensor.chargeurvoiture_status', 'Charging') }}" # La voiture ne charge pas déjà
                  sequence:
                    # Démarrer la charge
                    - service: select.select_option
                      data:
                        entity_id: select.chargeurvoiture_toggle_charging
                        option: "Start charging"
            # Si la batterie de la Zoé dépasse le seuil défini, arrêter la charge
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ states('sensor.fl995hk_batterie') | float >= states('input_number.zoe_coupure_pourcentage') | float }}" # Batterie Zoé au-dessus du seuil défini
                    - condition: template
                      value_template: "{{ is_state('sensor.chargeurvoiture_status', 'Charging') }}" # La voiture est en charge
                  sequence:
                    # Arrêter la charge
                    - service: select.select_option
                      data:
                        entity_id: select.chargeurvoiture_toggle_charging
                        option: "Stop charging"


################### Mode "Heures-Creuses" : Gestion pendant les heures creuses ###################
################### J'utilise sur mon compteur electrique un LIXEE - Module TIC qui remonte les moment ou le courant est moins chere, mais vous pouvez utiliser des horraires fixe.
       
- conditions:
    - condition: template
      value_template: "{{ is_state('input_select.SelecteurChargeurVE', 'Heures-Creuses') }}"
  sequence:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ states('sensor.linky_relais') == '1' }}"  # Vérifie que c'est les heures creuses
          sequence:
            - service: select.select_option
              data:
                entity_id: select.voltronic_1_param01
                option: "UTI"  # Passer en mode UTI (GRID)
            - delay:
                seconds: 30  # Attendre 30 secondes après avoir passé en mode UTI

    - choose:
        # Démarrer la charge pendant les heures creuses
        - conditions:
            - condition: template
              value_template: "{{ states('sensor.linky_relais') == '1' }}"
            - condition: template
              value_template: "{{ states('sensor.fl995hk_batterie') | float < states('input_number.zoe_coupure_pourcentage') | float }}"
            - condition: template
              value_template: "{{ not is_state('sensor.chargeurvoiture_status', 'Charging') }}"
          sequence:
            - service: select.select_option
              data:
                entity_id: select.chargeurvoiture_toggle_charging
                option: "Start charging"

        # Arrêter la charge si la batterie est au-dessus du seuil
        - conditions:
            - condition: template
              value_template: "{{ states('sensor.linky_relais') == '1' }}"
            - condition: template
              value_template: "{{ states('sensor.fl995hk_batterie') | float >= states('input_number.zoe_coupure_pourcentage') | float }}"
            - condition: template
              value_template: "{{ is_state('sensor.chargeurvoiture_status', 'Charging') }}"
          sequence:
            - service: select.select_option
              data:
                entity_id: select.chargeurvoiture_toggle_charging
                option: "Stop charging"

        # Arrêter la charge pendant les heures pleines
        - conditions:
            - condition: template
              value_template: "{{ states('sensor.linky_relais') == '0' }}"  # Heures pleines
            - condition: template
              value_template: "{{ is_state('sensor.chargeurvoiture_status', 'Charging') }}"
          sequence:
            - service: select.select_option
              data:
                entity_id: select.chargeurvoiture_toggle_charging
                option: "Stop charging"
            - delay:
                seconds: 10

            # Passer en mode SBU si la batterie de la maison est supérieure à 30%
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ states('sensor.voltronic_1_batt_battery') | float > 30 }}"
                  sequence:
                    - delay:
                        seconds: 30  # Attendre 30 secondes avant de passer en mode SBU
                    - service: select.select_option
                      data:
                        entity_id: select.voltronic_1_param01
                        option: "SBU"  # Passer en mode SBU (batterie)

    # Nouvelle condition ajoutée pour arrêter la charge en dehors des heures creuses
    - conditions:
        - condition: template
          value_template: "{{ states('sensor.linky_relais') == '0' }}"  # Vérifie que ce ne sont pas les heures creuses
        - condition: state
          entity_id: sensor.chargeurvoiture_status
          state: 'Charging'
      sequence:
        - service: select.select_option
          data:
            entity_id: select.chargeurvoiture_toggle_charging
            option: "Stop charging"





##################### Mode "Solaire" : Gestion basée sur la production solaire###################################
        - conditions:
            - condition: template
              value_template: "{{ is_state('input_select.SelecteurChargeurVE', 'Solar') }}"
          sequence:
            - choose:
                # Vérifier si on est dans la période solaire autorisée
                - conditions:
                    - condition: sun
                      after: sunrise
                      after_offset: '01:00:00' # 1 heure après le lever du soleil
                      before: sunset
                      before_offset: '-01:00:00' # 1 heure avant le coucher du soleil
                  sequence:
                    - choose:
                        # Démarrer la charge à 8A si elle n'est pas déjà en cours
                        - conditions:
                            - condition: template
                              value_template: "{{ not is_state('sensor.chargeurvoiture_status', 'Charging') }}" # La voiture ne charge pas déjà
                          sequence:
                            # Démarre la charge
                            - service: select.select_option
                              data:
                                entity_id: select.chargeurvoiture_toggle_charging
                                option: "Start charging"
                            # Définit le courant de charge à 8A
                            - service: input_number.set_value
                              data:
                                entity_id: input_number.chargeurvoiture_set_charge_current
                                value: 8
                    # Boucle pour ajuster le courant de charge en fonction de la puissance solaire
                    - repeat:
                        while:
                          - condition: and
                            conditions:
                              - condition: state
                                entity_id: sensor.chargeurvoiture_status
                                state: 'Charging' # Tant que la voiture est en charge
                              - condition: sun
                                after: sunrise
                                after_offset: '01:00:00' # Dans la période solaire autorisée
                                before: sunset
                                before_offset: '-01:00:00'
                        sequence:
                          # Attend un changement de la puissance solaire
                          - wait_for_trigger:
                              - platform: state
                                entity_id: sensor.combined_power_pylontech_voltronic
                          # Définition des variables locales
                          - variables:
                              power: "{{ states('sensor.combined_power_pylontech_voltronic') | float }}" # Puissance solaire disponible
                              current: "{{ states('input_number.chargeurvoiture_set_charge_current') | float }}" # Courant de charge actuel
                          - choose:
                              # Si la puissance est négative (consommation supérieure à la production)
                              - conditions:
                                  - condition: template
                                    value_template: "{{ power < 0 }}"
                                sequence:
                                  - choose:
                                      # Si le courant est supérieur à 8A, on le réduit de 1A
                                      - conditions:
                                          - condition: template
                                            value_template: "{{ current > 8 }}"
                                        sequence:
                                          # Réduit le courant de charge de 1A
                                          - service: input_number.set_value
                                            data:
                                              entity_id: input_number.chargeurvoiture_set_charge_current
                                              value: "{{ current - 1 }}"
                                      # Si le courant est déjà à 8A, on attend 30s et on arrête la charge
                                      - conditions:
                                          - condition: template
                                            value_template: "{{ current == 8 }}"
                                        sequence:
                                          # Attendre 30 secondes
                                          - delay: "00:00:30"
                                          # Arrêter la charge
                                          - service: select.select_option
                                            data:
                                              entity_id: select.chargeurvoiture_toggle_charging
                                              option: "Stop charging"
                                          # Stopper la boucle avec un message
                                          - stop: "La charge est arrêtée car la puissance solaire est insuffisante."
                              # Si la puissance est positive (production supérieure à la consommation)
                              - conditions:
                                  - condition: template
                                    value_template: "{{ power > 0 }}"
                                sequence:
                                  - choose:
                                      # Si le courant est inférieur à 32A, on l'augmente de 1A
                                      - conditions:
                                          - condition: template
                                            value_template: "{{ current < 32 }}"
                                        sequence:
                                          # Augmente le courant de charge de 1A
                                          - service: input_number.set_value
                                            data:
                                              entity_id: input_number.chargeurvoiture_set_charge_current
                                              value: "{{ current + 1 }}"
                          # Attendre 5 secondes avant la prochaine vérification
                          - delay: "00:00:07"
                # Si on est en dehors de la période solaire autorisée
                - conditions:
                    - condition: not
                      conditions:
                        - condition: sun
                          after: sunrise
                          after_offset: '01:00:00'
                          before: sunset
                          before_offset: '-01:00:00'
                    - condition: state
                      entity_id: sensor.chargeurvoiture_status
                      state: 'Charging' # La voiture est en charge
                  sequence:
                    # Arrêter la charge
                    - service: select.select_option
                      data:
                        entity_id: select.chargeurvoiture_toggle_charging
                        option: "Stop charging"

###################### Mode "Off" : Arrêt de la charge meme si quelqu'un ce branche
        - conditions:
            - condition: template
              value_template: "{{ is_state('input_select.SelecteurChargeurVE', 'Off') }}"
          sequence:
            - choose:
                # Si la voiture est en charge, on arrête la charge
                - conditions:
                    - condition: state
                      entity_id: sensor.chargeurvoiture_status
                      state: 'Charging'
                  sequence:
                    # Arrêter la charge
                    - service: select.select_option
                      data:
                        entity_id: select.chargeurvoiture_toggle_charging
                        option: "Stop charging"

  mode: single # Empêche l'automatisation de s'exécuter en parallèle
